services:
  frontend:
    build: ./flight_booking_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - keycloak

  backend:
    build: ./flight_booking_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/flight-booking
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/flight-booking/protocol/openid-connect/certs
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  mysql_data:
  keycloak_data:
